### ISSUE TITLE
Add vcd-cli commands for taking snapshots

### ISSUE THREAD

**Issue by fnoorden-vs** [vmware/vcd-cli#204]
vcd-cli is missing commands to handle snapshots of vapp's and vm's.

Are those on the roadmap?

**Comment by fnoorden-vs** [comment]
I just found out that there is some code regarding to snapshots, but not completely implemented in the cli:
[root@mgt vcd]# grep "snap" *
client.py:    SNAPSHOT_CREATE = 'snapshot:create'
client.py:    SNAPSHOT_REVERT_TO_CURRENT = 'snapshot:revertToCurrent'
client.py:    SNAPSHOT_REMOVE_ALL = 'snapshot:removeAll'

vm.py:    def snapshot_create(self, memory=None, quiesce=None, name=None):
vm.py:        :param memory: (bool): True if the snapshot should include the
vm.py:            should be quiesced before the snapshot is created.
vm.py:        snapshot_vm_params = E.CreateSnapshotParams()
vm.py:            snapshot_vm_params.set('memory', str(memory).lower())
vm.py:            snapshot_vm_params.set('quiesce', str(quiesce).lower())
vm.py:            snapshot_vm_params.set('name', str(name).lower())
vm.py:            EntityType.SNAPSHOT_CREATE.value, snapshot_vm_params)
vm.py:    def snapshot_revert_to_current(self):
vm.py:        """Reverts a virtual machine to the current snapshot, if any.
vm.py:    def snapshot_remove_all(self):
vm.py:        """Removes all user created snapshots for a virtual machine.

**Comment by hodgesrm** [comment]
Thanks for the Issue.  We would definitely like more snapshot features so yes this is on the roadmap, but it may take a while.  The existing support came from a couple of external PRs on pyvcloud (https://github.com/vmware/pyvcloud/pull/206, https://github.com/vmware/pyvcloud/pull/199).

If you or anyone else would like to add more snapshot features we would be delighted to review and merge the PR.  Please follow the model implemented in the referenced pull requests to add vApp snapshot functionality (e.g., to vapp.py), then do another PR to add vm and vapp commands to vcd-cli. 

Internally we're focused on improving CI/CD and unit tests so that users can contribute more easily, followed by more networking features. Improving snapshots will probably come after that unless somebody jumps in before us.  

Cheers, Robrt

**Comment by fnoorden-vs** [comment]
I have created the snapshot features create, delete and revert and I am ready to submit them. I also developed a list snapshot feature, but that is not (yet) supported by pyvcloud.  Meaning that some code that should be in pyvcloud, is now added to vcd-cli. 

How do I handle this? 
A. drop the list snapshot feature
B. include the code that should be in pycloud in vcd-cli

Like to hear from you!

**Comment by hodgesrm** [comment]
Hi @fnoorden-vs!

The best approach is to do a separate PR for pyvcloud and get that in first.  We need to avoid cluttering vCD CLI with API-level functions.  I can review this for you very quickly so it should not delay things much. 

Failing that I would vote for (A) rather than put new code in the wrong place. 

Cheers, Robert

**Comment by rohitgabriel** [comment]
Hi @fnoorden-vs 
Were you able to submit the code for snapshot features? Or any other repo we can get it from?

**Comment by mblag** [comment]
Hi @hodgesrm and @fnoorden-vs has that enhancement request been implemented? Thanks in advance.

**Comment by fnoorden-vs** [comment]
Due to a switch to PowerCLI I didn't substitute code. I will attach the code today to this issue.

**Comment by vikramarsid** [comment]
@fnoorden-vs Please pardon me, will you be able to open a PR for VM snapshot changes? If not, I can an open a PR with VM snapshot operations. TIA.

**Comment by swerveshot** [comment]
> Due to a switch to PowerCLI I didn't submit code. I will attach the code today to this issue.

Same goes for PowerCLI; vCloud capabilities for creating and managing snapshot is completely absent. Any suggestions on how to get this implemented?

**Comment by pasikarkkainen** [comment]
any news here?

**Comment by pandeys** [comment]
snapshot features for vApp and VM are implemented in new release. pyvcloud and vcd-cli git hub repositories has corresponding methods in vm.py.

**Comment by swerveshot** [comment]
The [vcd-cli documentation](http://vmware.github.io/vcd-cli/commands.html) already shows snapshot support for both vApps and VMs. But it's good to know that pyvcloud is being enhanced. This makes snapshot support for the Ansible vCD provider possible as well.

I've raised an issue requesting this feature some time ago.
vmware/ansible-module-vcloud-director#51

**Comment by swerveshot** [comment]
Can you give out any details on when the next pyvcloud release is expected @pandeys?
