### ISSUE TITLE
vcd login command behavior is different for v33.0 and v32.0

### ISSUE THREAD

**Issue by rocknes** [vmware/vcd-cli#487]
(cse) C:\code\container-service-extension>vcd login [vcd 9.8 ip] system administrator -iwp [super secret]
administrator logged in, org: 'system', vdc: 'cse-orgvdc'

(cse) C:\code\container-service-extension>vcd login [vcd 9.8 ip] system administrator -iwp [super secret] -V 32.0
administrator logged in, org: 'system', vdc: ''

The vdc that is chosen by default while using api v33 is wrong.
vCD used : 9.8 testfest 1 build.

Regards
Aritra Sen

**Comment by pandeys** [comment]
Hi Aritra,

This issue is fixed by Kishan. Current behavior is similar for both API VERSION login:

vcd login <VCD-IP> system administrator -p ****** -i -w
administrator logged in, org: 'system', vdc: ''

vcd login <VCD-IP> system administrator -p ****** -i -w -V 32.0
administrator logged in, org: 'system', vdc: ''

Thanks,
Saurabh
